### PR TITLE
update camera

### PR DESCRIPTION
**Pull request by kraiby30**

### CODE REVIEW

**Comment by keryell** [comment]
It compiles but it looks like it takes forever to run.
Perhaps this is because we do not look at the same place as before without the camera?

**Comment by keryell** [comment]
Actually it finished after 10 minutes on my laptop
```
RT_SYCL/sycl-rt >| result.ppm  6295.97s user 7.84s system 1013% cpu 10:21.74 total
```
but the result is probably wrong, even if there are some ideas...
result

**Comment by keryell** [comment]
Thank you, it works quite better.
Can you fix all the warning messages related to `will be initialized after [-Wreorder]`?
Thanks.

**Comment by kraiby30** [comment]
Yes, Ill look into it!

**Pull request merged**
